services:
  backend-klontong:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: always
    depends_on:
      - db-klontong
      - minio
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      POSTGRES_HOST: db-klontong
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: klontong
      MINIO_ENDPOINT: localhost
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: 3NxpyPysT7L43zTU07Ys
      MINIO_SECRET_KEY: ThfzkoY7LssXnuc7hxYd0XfbmWjBO4LniDptEihv
      MINIO_BUCKET: main
      MINIO_USE_SSL: 'false'
    networks:
      - be
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /app
  db-klontong:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/logs:/var/log/postgresql
      - ./data/config:/etc/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: klontong
    ports:
      - '54323:5432'
    networks:
      - be
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: paleo
      MINIO_ROOT_PASSWORD: paleo
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_DEFAULT_BUCKET: main
    volumes:
      - ./data/minio:/bitnami/minio/data
    networks:
      - be

networks:
  be:
    driver: bridge
